#!/bin/bash

progress() {
    echo -e "$(tput bold)\n$1$(tput sgr0)"
}

expenv() {
    if [ "$1" == "--append" ]; then
        echo "export" $2"=\${"$2":+\${"$2"}:}"$3 >> ~/.bashrc
    else
        echo "export" $1"="$2 >> ~/.bashrc
    fi
}


cd $(dirname "$0")
set -e

if [ "$(grep -IGnr "YOUR[_A-Z]\+")" != "" ]; then
    progress "Please fill up belows before running this script"
    grep -IGnr "YOUR[_A-Z]\+"
    exit
fi

homedir=/home/ubuntu
expenv "MLP_HOME" "${homedir}/"

efs_mount_point=${homedir}/efs
efs_dns_name="YOUR_EFS_DNS_NAME"


# Install prerequisites
progress "Install Prerequisites"

sudo apt-get update
sudo apt-get install -y --no-install-recommends linux-headers-$(uname -r)
sudo apt-get install -y --no-install-recommends gcc


# Install NFS Client (https://docs.aws.amazon.com/efs/latest/ug)
progress "Install NFS Client"

sudo apt-get -y --no-install-recommends install nfs-common


# Install Golang 1.9 (https://github.com/golang/go/wiki/Ubuntu)
progress "Install Golang 1.9"

sudo add-apt-repository -y ppa:gophers/archive
sudo apt-get update
sudo apt-get install -y --no-install-recommends golang-1.9-go

mkdir ~/.go

expenv --append "PATH" "/usr/lib/go-1.9/bin"
expenv "GOPATH" "\$HOME/.go"

export PATH=${PATH:+${PATH}:}/usr/lib/go-1.9/bin
export GOPATH=$HOME/.go

go version


# Setup
# : Set learning environment on the instance
progress "Setup environment in ${homedir}"

mkdir ${homedir}/efs ${homedir}/script

go get github.com/gorilla/mux
go get github.com/aws/aws-sdk-go
go build -o ${homedir}/manage manage.go
cp userdata_template upload.html ${homedir}/script

mnt_o="nfsvers=4.1,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2,_netdev"

echo "${efs_dns_name}:/	${efs_mount_point}	nfs4	${mnt_o}	0 0" |\
    sudo tee -a /etc/fstab

progress "Reboot this instance to finish setup."
