#!/bin/bash

# Same environment variables as those in '~/.bashrc' of instance
export MLP_HOME=/home/ubuntu
export DOCKER_API_VERSION=1.35

manager_addr=YOUR_MANAGER_PUBLIC_IP_ADDR

wrap_up() {
    cp /var/log/syslog ${MLP_HOME}/efs/user/token_dat/output/syslog
    chown ubuntu:ubuntu ${MLP_HOME}/efs/user/token_dat/output/syslog

    sync
    halt
}

trap 'wrap_up' ERR
exec 1> >(logger -t user-data) 2>&1

cp ${MLP_HOME}/efs/user/token_dat/src/main.py ${MLP_HOME}/src/main.py
${MLP_HOME}/runcontainer token_mod token_lib token_dat

wrap_up
