#!/bin/bash

# Same environment variables as those in '~/.bashrc' of instance
export MLP_HOME=/home/ubuntu
export DOCKER_API_VERSION=1.35

manager_addr=YOUR_MANAGER_PUBLIC_IP_ADDR

send_status_to_manager() {
    curl -X PUT -d status=$1 $manager_addr:8080/status
}

wrap_up() {
    if [ "$1" == "err" ]; then
        send_status_to_manager "error"
    fi

    send_status_to_manager "halt"
    sync
    halt
}

trap 'wrap_up err' ERR

send_status_to_manager "initialized"

tensorboard --logdir=${MLP_NOME}/efs/user/token_dat/tensorboard &
cp ${MLP_HOME}/efs/user/token_dat/src/main.py ${MLP_HOME}/src/main.py

send_status_to_manager "container"

${MLP_HOME}/runcontainer token_mod token_lib token_dat

wrap_up
