#!/bin/bash

progress() {
    echo -e $(tput bold)$1$(tput sgr0)
}

homedir=/home/ubuntu/

# Initialization
# : Move directory to 'learner' and get some primary resources.
progress "Move working directory to $(dirname "$0")"
cd $(dirname "$0")

sudo apt-get update
sudo apt-get install -y --no-install-recommends linux-headers-$(uname -r)
sudo apt-get install -y --no-install-recommends gcc


# Install CUDA 9.1
# Reference: https://developer.nvidia.com/cuda-downloads
progress "Install CUDA 9.1"

cuda_repo=http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64
cuda_deb=cuda-repo-ubuntu1604_9.1.85-1_amd64.deb

wget ${cuda_repo}/${cuda_deb}
sudo dpkg -i ${cuda_deb}
sudo apt-key adv --fetch-keys ${cuda_repo}/7fa2af80.pub
sudo apt-get update
sudo apt-get install -y --no-install-recommends cuda
rm ${cuda_deb}*

nvidia-smi


# Install Golang 1.9
# Reference: https://github.com/golang/go/wiki/Ubuntu
progress "Install Golang 1.9"

sudo add-apt-repository -y ppa:gophers/archive
sudo apt-get update
sudo apt-get install -y --no-install-recommends golang-1.9-go

mkdir ~/.go
echo "export PATH=\$PATH:/usr/lib/go-1.9/bin" >> ~/.bashrc
echo "export GOPATH=\$HOME/.go" >> ~/.bashrc

export PATH=$PATH:/usr/lib/go-1.9/bin
export GOPATH=$HOME/.go

go version


# Install Docker
# Reference: https://docs.docker.com/install/linux/docker-ce/ubuntu/
progress "Install Docker CE"

sudo apt-get install -y --no-install-recommends \
    apt-transport-https \
    ca-certificates \
    curl \
    software-properties-common
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
sudo add-apt-repository \
    "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
    $(lsb_release -cs) \
    stable"
sudo apt-get update
sudo apt-get install -y --no-install-recommends docker-ce
sudo usermod -aG docker $USER

sudo docker version


# Install NVIDIA-Docker 2.0
# Reference: https://github.com/nvidia/nvidia-docker/wiki/Installation-(version-2.0)
progress "Install NVIDIA Docker 2.0"

curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | sudo apt-key add -
curl -s -L https://nvidia.github.io/nvidia-docker/ubuntu16.04/amd64/nvidia-docker.list | sudo tee /etc/apt/sources.list.d/nvidia-docker.list
sudo apt-get update
sudo apt-get install -y --no-install-recommends nvidia-docker2
sudo pkill -SIGHUP dockerd


# Setup
#
echo ""
progress "Setup learner environment in ${homedir}"

progress " - make directories"

mkdir ${homedir}/src ${homedir}/dat ${homedir}/out ${homedir}/tbl

progress " - copy resources"

go get github.com/docker/docker/client
go build -o ${homedir}/runcontainer runcontainer.go
cp train save_model.py ${homedir}/src/

progress " - build docker images"

cd ./dockerfile
sudo ./build tensorflow
sudo docker images

echo ""
progress "#########################################"
progress "# REBOOT THIS INSTANCE TO FINISH SETUP. #"
progress "#########################################"
