#!/bin/bash

show_help() {
    echo "usage: build library"
    echo "library:"

    for lib in ${libs[@]}; do
        printf "  %s\n" "$lib"
    done

    exit
}

is_available_library() {
    for lib in ${libs[@]}; do
        if [ $1 = $lib ]; then
            return 1
        fi
    done

    return 0
}

libs=(
    "tensorflow"
)

if [ $# -lt 1 ]; then
    show_help
fi

if is_available_library $1 ; then
    echo "error: $1 is not available library."
    show_help
fi

cwd=$(pwd)
lib=$1

echo "$1: Build docker image from dockerfile..."
docker build -t $lib -f $lib.Dockerfile .
